### ISSUE TITLE
User number of stars on repos

### ISSUE THREAD

**Issue by TheWillG** [TheWillG/github-profile-summary-api#25]
- [ ] query user's total number of stars for all the repos they are an owner of

**Comment by himanshu2408** [comment]
I am Interested

**Comment by theblindprophet** [comment]
@himanshu2408 This should be fairly simple. Check out the Github API v4 docs.

**Comment by TheWillG** [comment]
This is in collaboration with https://github.com/theblindprophet/github-profile-summary/issues/30

**Comment by lourdesr** [comment]
Is this still up for grabs ? If yes, can I have a go at it?

**Comment by TheWillG** [comment]
Hi @lourdesr, yes we are still awaiting a PR so if you submit it first we will accept yours.

**Comment by theblindprophet** [comment]
Update requirements. Misunderstanding.

**Comment by lourdesr** [comment]
Hey @TheWillG - thanks, I'm on it.

**Comment by lourdesr** [comment]
Hi @TheWillG - I just setup the codebase. I ran all the tests. Set up token in env. I've never used graphql before, so I'm reading some docs and going through the codebase. Hopefully I'll have a fix soon.

**Comment by TheWillG** [comment]
Sounds good. Once you get your personal access token and add it to the env file locally, the app should run.  The env-example is an example of this.
A good way to prototype the queries is to use the GraphQL explorer https://developer.github.com/v4/explorer/

**Comment by lourdesr** [comment]
Hey @TheWillG, 

Thank you. Since I am a beginner, it's taking some time to work through this but I am slowly getting the hang of it. Below are the steps I plan to follow to complete this. I'd appreciate any sort of advice/feedback. 

1. Add this query under 'node'
`stargazers {
            totalCount
          }`

2. Call a function with the 'userName' and the 'graphQlResponse' object
3. I am assuming, by passing the right graphQlResponse object (example.  `.value.data.user.repositories.edges` ) I can parse the stargazer attribute. 
4. After that, I can just map over this and find the total. 

P.S. Is there a way to test this out and print it to my console ? It'll make my coding a lot easier. 

Thank you! :)
